# Generated by Django 5.2.1 on 2025-06-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='equipment',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
    ]
